#!/bin/bash
# -----------------------------------------------------------------------------
# Author: Sam Whang
# File  : install.sh
# Date  : 07/17/17
# -----------------------------------------------------------------------------

# fast install -- used for reinstallation to only copy new version of tp over to bin directory
if [[ $# == "1" && $2 == $(getopts "a" opt) ]]; then
    cp tp /usr/local/bin > /dev/null 2>&1 || { echo "Installed Failed: Try Install With Sudo"; exit 1; }
    exit 0
fi

# need to check if tp file exists in directory
if [ ! -f $PWD/tp ]; 
then
    echo -e "File doesn't exist\nExitting" && exit 1
fi

# need to check directory we are copying to
if [ ! -d /usr/local/bin ]; 
then
    echo -n "Creating necessary folders '/usr/local/bin' "
    mkdir /usr/local/bin > /dev/null 2>&1 || { echo " | nested layers"; mkdir /usr/local; mkdir /usr/local/bin; }
fi

# make script executable and copy to bin or path
chmod a+x tp
cp tp /usr/local/bin > /dev/null 2>&1 || { echo "Install Failed: Try Install With Sudo"; exit 1; }

# checks file level then dir level to make sure existance of tp directory
if [ ! -f ~/.teleport/.tp_aliases ]; 
then
    if [ ! -d ~/.teleport ];
    then 
        mkdir ~/.teleport
    fi
    touch ~/.teleport/.tp_aliases
fi

# checks bashrc for existance or previous install of teleport
if [ ! -f ~/.bashrc ]; 
then
    touch ~/.bashrc
fi  

# if bashrc exists looks for tp command, inserts if unfound
if ! grep -q "source ~/.teleport/.tp_aliases" ~/.bashrc; 
then
    echo "if [ -f ~/.teleport/.tp_aliases ];" >> ~/.bashrc
    echo "then" >> ~/.bashrc
    echo "    source ~/.teleport/.tp_aliases" >> ~/.bashrc
    echo "fi" >> ~/.bashrc
fi
echo "teleport install complete"
