#!/bin/bash
# -----------------------------------------------------------------------------
# Author: Sam Whang
# File  : tp.sh
# Date  : 07/17/17
# -----------------------------------------------------------------------------


usage()
{
    echo "TP"
    echo "Description A simple cl tool to change directories"
    echo 	"-a [dir name]            Add directory to teleport list"
    echo	"-d [dir name]            Remove directory from list$"
    echo	"-g                       Get all directories from list and print name"
    echo	"-h                       Prints help/usage string"
    echo	"-m [dir name] [dir name] Move/Rename name in list to a different name"
    echo	"-r [dir name]            Remove directory name from list"
    echo	"-R Remove all            directories"
    echo	"-t [dir name]            Test directory name by printing full path of directory"
    echo	"-u                       Update teleport"
    echo	"-v                       Print current version of teleport"
}


version()
{
    echo "TP version: 0.0.1"
}


make()
{
    # checks file level then dir level to make sure existance of tp directory
    if [ ! -f ~/.teleport/directories.txt ]; then
        if [ ! -d ~/.teleport ]; then 
          mkdir ~/.teleport
        fi
        touch ~/.teleport/directories_aliases
    fi
}

load()
{
    # load aliases into shell by sourcing alias file
    source ~/.teleport/directories_aliases
}


push()
{
    make
    echo -e "alias $1=$PWD" >> ~/.teleport/directories_aliases
    echo "Created TP Link: $1"
    load
}


pull()
{
    make
    echo "$1"
    #set -i.bak '/"$(2)/d' ~/.teleport/directories_aliases
}


pullAll()
{
    
    rm -f ~/.teleport/directories_aliases
    touch ~/.teleport/directories_aliases
    echo "Cleared TP Locations"
}


# checks for empty args
echo $(uname)
echo $HOME
if [[ $# == "0" ]]; then
    usage
    exit 0
fi


# parses input args
while getopts "r:Ra:hvu" opt; do
    case $opt in
        \?)
            
            echo "Invalid option -$OPTARG" >&2 && exit -1
        ;;
        h)
            usage && exit 0
        ;;
        v)
            version && exit 0
        ;;
        a)
            echo "add name" && push "$2" && exit 1
        ;;
        r)
            echo "remove name" && pull "$2" && exit 1
        ;;
        R)
            echo "Delete All" && pullAll && exit 1
        ;;
        u)
            echo "undo deletion" && exit 1
        ;;
    esac
done
