#!/bin/bash
# -----------------------------------------------------------------------------
# Author: Sam Whang
# File  : uninstall.sh
# Date  : 07/17/17
# -----------------------------------------------------------------------------

# check if install even exists
if [ -d ~/.teleport ];
then
    if [[ -s ~/.teleport/aliases ]]; then
      while IFS='=' read -r line || [[ -n "$line" ]];
      do 
        word=$(echo "$line" | awk '{split($2,a,"="); print a[1]}')
        [[ $(type -t $word) == "alias" ]] && unalias $word
      done < ~/.teleport/aliases
    fi
    for file in ~/.teleport/*; do
      rm "$file"
    done
    rmdir ~/.teleport
fi

# checks for teleport script in bashrc
if [[ -f ~/.bashrc ]] && $(grep -q "~d /.teleport" ~/.bashrc); then
    sed -i.bak '/\-d \~\/.teleport/,+3d' ~/.bashrc
fi
echo "teleport uninstall complete"
